### ISSUE TITLE
Ability to run a test on specific groups only

### ISSUE THREAD

**Issue by jasonyates** [dmulyalin/nornir-salt#9]
I have a host file defining many network devices and I have a test suite defining many tests. Some tests are only relevant for some devices. It would be useful to allow individual tests to be scoped to individual devices or device groups.

**Comment by dmulyalin** [comment]
Have a look at using jinja2 to construct tests e.g.
```
{% if "foo" in host.groups%}
Bla
{% endif%}
```
https://nornir-salt.readthedocs.io/en/latest/Processors/TestsProcessor.html#using-tests-suite-templates
